from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    CAMERA_CONNECT_FAIL = "CAMERA_CONNECT_FAIL"
    MODEL_INIT_FAIL = "MODEL_INIT_FAIL"
    FAISS_LOAD_FAIL = "FAISS_LOAD_FAIL"
    FAISS_REBUILD_FAIL = "FAISS_REBUILD_FAIL"
    QUEUE_OVERFLOW = "QUEUE_OVERFLOW"
    FRAME_PROCESS_FAIL = "FRAME_PROCESS_FAIL"
    CONFIG_LOAD_FAIL = "CONFIG_LOAD_FAIL"
    IO_WRITE_FAIL = "IO_WRITE_FAIL"

